# Generated by Django 4.2.28 on 2026-02-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('last_updated_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='use this for soft deleting')),
                ('value', models.IntegerField(help_text='The currency denomination value', unique=True)),
                ('available_count', models.IntegerField(default=0, help_text='The amount available')),
            ],
            options={
                'verbose_name': 'Amount Denomination',
                'verbose_name_plural': 'Amount Denominations',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('last_updated_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='use this for soft deleting')),
                ('code', models.CharField(db_index=True, help_text='The product code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='The product name', max_length=200)),
                ('stock_quantity', models.IntegerField(default=0, help_text='The product stock quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='The product unit price', max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, help_text='The product tax percentage', max_digits=5)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('last_updated_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='use this for soft deleting')),
                ('code', models.CharField(db_index=True, help_text='Unique identification for Order', max_length=25, unique=True)),
                ('customer_email', models.EmailField(db_index=True, help_text='Customer Email', max_length=254)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Date of purchase')),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_sent', models.BooleanField(default=False, help_text='Invoice sent or not identification')),
                ('invoice_sent_at', models.DateTimeField(blank=True, help_text='Invoice sent at', null=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, help_text='Tax percentage', max_digits=5)),
                ('product', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.RESTRICT, to='billing.product')),
                ('purchase', models.ForeignKey(help_text='Purchase order', on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_items', to='billing.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='ChangeDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing.amountdenomination')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='change_denominations', to='billing.purchaseorder')),
            ],
            options={
                'verbose_name': 'Change Denomination',
                'verbose_name_plural': 'Change Denominations',
                'ordering': ['-denomination__value'],
                'unique_together': {('purchase', 'denomination')},
            },
        ),
    ]
