# Generated by Django 4.2.28 on 2026-02-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('type', models.CharField(choices=[('paid', 'Paid by Customer'), ('balance', 'Balance to Customer')], max_length=10)),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing.amountdenomination')),
            ],
            options={
                'verbose_name': 'Denomination Detail',
                'verbose_name_plural': 'Denomination Details',
                'ordering': ['-denomination__value'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Is draft?'),
        ),
        migrations.DeleteModel(
            name='ChangeDenomination',
        ),
        migrations.AddField(
            model_name='denominationdetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='denomination_details', to='billing.purchaseorder'),
        ),
        migrations.AlterUniqueTogether(
            name='denominationdetail',
            unique_together={('purchase', 'denomination', 'type')},
        ),
    ]
